# Generated by Django 4.0.6 on 2022-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tt',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
